In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
my_list = [1,2,3,4,5,6]
print(my_list)

[1, 2, 3, 4, 5, 6]


In [5]:
import numpy as np

In [6]:
array = np.array(my_list, dtype = int)
print(array)

[1 2 3 4 5 6]


In [7]:
print(type(array))
print(len(array))
print(array.ndim)
print(array.shape)

<class 'numpy.ndarray'>
6
1
(6,)


In [8]:
array2 = array.reshape(3,2)
print(array2)
array2.shape

[[1 2]
 [3 4]
 [5 6]]


(3, 2)

In [9]:
array3 = array.reshape(3, -1)
print(array3)
print(array3.ndim)

[[1 2]
 [3 4]
 [5 6]]
2


In [11]:
my_list2 = [1,2,3,4,5]
my_list3 = [2,3,4,5,6]
my_list4 = [9,7,6,8,9]

mul_arr = np.array([my_list2, my_list3, my_list4])
print(mul_arr)

print(mul_arr.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 7 6 8 9]]
(3, 5)


In [12]:
mul_arr.reshape(1,15)

array([[1, 2, 3, 4, 5, 2, 3, 4, 5, 6, 9, 7, 6, 8, 9]])

In [13]:
a = np.array([[1,2,3], [4,5,6]])
print(a.shape)

(2, 3)


In [14]:
# reshaping the ndarray
a.shape = (3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [15]:
r = range(24)

In [16]:
print(r)

range(0, 24)


In [18]:
a = np.arange(24)
print(a)
print(a.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1


In [20]:
b = a.reshape(6, 4, 1)
print(b)

[[[ 0]
  [ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]
  [ 7]]

 [[ 8]
  [ 9]
  [10]
  [11]]

 [[12]
  [13]
  [14]
  [15]]

 [[16]
  [17]
  [18]
  [19]]

 [[20]
  [21]
  [22]
  [23]]]


In [21]:
x = np.array([1,2,3,4,5], dtype = np.float32)
print(x.itemsize)

4


In [22]:
x = np.array([[1,2], [3,4]], dtype=np.float64)
y = np.array([[5,6], [7,8]], dtype=np.float64)
print(x)
print(y)

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]


In [23]:
print(x + y)
print(np.add(x,y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [24]:
print(x - y)
print(np.subtract(x,y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [25]:
print(x * y)
print(np.multiply(x,y))
print(x.dot(y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[19. 22.]
 [43. 50.]]


In [26]:
print(x.dot(y))
print(np.dot(x,y))

[[19. 22.]
 [43. 50.]]
[[19. 22.]
 [43. 50.]]


In [27]:
print(x/y)
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [28]:
print(np.sum(x))

10.0


In [29]:
print(np.sum(x, axis=0))
print(np.sum(x, axis=1))

[4. 6.]
[3. 7.]


### Numpy Exercises

In [30]:
#print(np._version_)
np.show_config

<function numpy.__config__.show()>

In [31]:
#create a null vector of size 10
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [32]:
#null vector of size whose value is 1
Z = np.arange(50)
Z = Z[::-1]

In [33]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [34]:
Z = np.arange(50)
Z = Z[::-1]

In [35]:
import numpy as np
rows = int(input("Enter the number of rows: "))
cols = int(input("Enter the number of columns: "))

user_array = np.empty((rows, cols), dtype=int)
for i in range(rows):
    for j in range(cols):
        user_array[i, j] = int(input(f"Enter element at position ({i+1}, {j+1}): "))

print("\nOriginal Array:")
print(user_array)

reversed_array = user_array[:, ::-1]

print("\nReversed Array:")
print(reversed_array)

Enter the number of rows: 2
Enter the number of columns: 2
Enter element at position (1, 1): 1
Enter element at position (1, 2): 2
Enter element at position (2, 1): 3
Enter element at position (2, 2): 4

Original Array:
[[1 2]
 [3 4]]

Reversed Array:
[[2 1]
 [4 3]]


In [40]:
import numpy as np
rows = 3
cols = 4

random_array = np.random.uniform(5.0, 10.0, size=(rows, cols))
print(random_array)

[[8.0003149  5.81334771 7.81416118 9.43421559]
 [6.01202    7.90095796 6.3914896  7.5576884 ]
 [5.84384919 6.28085065 5.51468187 5.61298666]]


In [56]:
import numpy as np

def calculate_percentiles(inputarray, percentiles):
  try:
    array = np.array([float(x) for x in inputarray.split(',')])
    if not all(0 <= p <= 100 for p in percentiles):
      raise ValueError("Percentiles must be between 0 and 100")
    percentile_scores = np.percentile(array, percentiles)
    for i in range(len(percentiles)):
      print(f"{percentiles[i]}th percentile: {percentile_scores[i]}")
  except ValueError as e:
    print("Error:", e)

# Get input from user
inputarray = input("Enter comma-separated values for the array: ")
pinput = input("Enter percentiles (comma-separated): ")
percentiles = [float(p) for p in pinput.split(',')]

# Calculate and print percentiles
calculate_percentiles(inputarray, percentiles)

TypeError: 'str' object is not callable

In [45]:
import numpy as np
array = np.array([1.0, 2.0, np.nan, 4.0, 5.0])
indices = np.where(np.isnan(array))
print("Indices of missing values:", indices)

Indices of missing values: (array([2], dtype=int64),)


In [43]:
import numpy as np
original_array = np.array([[3, 2, 5],
                           [1, 4, 6],
                           [7, 0, 8]])

sorted_array = original_array[original_array[:, 1].argsort()]
print("Original Array:")
print(original_array)

print("\nSorted Array by Column 1:")
print(sorted_array)

Original Array:
[[3 2 5]
 [1 4 6]
 [7 0 8]]

Sorted Array by Column 1:
[[7 0 8]
 [3 2 5]
 [1 4 6]]


In [53]:
import numpy as np
array_of_arrays = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
flat_array = array_of_arrays.flatten()

print("Original 2D Array:")
print(array_of_arrays)

print("\nFlattened 1D Array:")
print(flat_array)

Original 2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Flattened 1D Array:
[1 2 3 4 5 6 7 8 9]


In [55]:
import numpy as np

# Sample data
data = np.array([1, 2, 3, 4, 5])

# Mean
mean = np.mean(data)
print("Mean:", mean)

# Median
median = np.median(data)
print("Median:", median)

# Mode
mode = np.argmax(np.bincount(data))
print("Mode:", mode)

# Standard deviation
std_dev = np.std(data)
print("Standard deviation:", std_dev)

# Euclidean distance (between first two elements)
euclidean_distance = np.linalg.norm(data[0] - data[1])
print("Euclidean distance:", euclidean_distance)

# Manhattan distance (between first two elements)
manhattan_distance = np.sum(np.abs(data[0] - data[1]))
print("Manhattan distance:", manhattan_distance)


Mean: 3.0
Median: 3.0
Mode: 1
Standard deviation: 1.4142135623730951
Euclidean distance: 1.0
Manhattan distance: 1
